### ISSUE TITLE
作者你好在评估时出现这个问题，请问您是怎么解决的呢

### ISSUE THREAD

**Issue by Lkevin20** [sansanfree/RBO#12]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/Lsiamban/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/liuhuan/RBO-main/SiamPW-RBO/toolkit/evaluation/ope_benchmark.py", line 192, in eval_success
    success_ret_[video.name] = success_overlap(gt_traj, tracker_traj, n_frame)
  File "/home/ubuntu/liuhuan/RBO-main/SiamPW-RBO/toolkit/utils/statistics.py", line 105, in success_overlap
    iou[mask] = overlap_ratio(gt_bb[mask], result_bb[mask])
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tools/eval.py", line 179, in <module>
    main()
  File "tools/eval.py", line 57, in main
    trackers), desc='eval success', total=len(trackers), ncols=100):
  File "/home/ubuntu/anaconda3/envs/Lsiamban/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/ubuntu/anaconda3/envs/Lsiamban/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

**Comment by sansanfree** [comment]
你好，你是自己测试出现这个问题吗？我没有出现这个问题，出现这个问题应该是groundtruth和预测框的长度不一样导致的。

**Comment by Lkevin20** [comment]
在作者您源代码的基础上取消了使用IGR loss,只使用CR loss，在Lasot数据集上训练，在OTB数据集测试后评估就出现这个错误

**Comment by sansanfree** [comment]
> 在作者您源代码的基础上取消了使用IGR loss,只使用CR loss，在Lasot数据集上训练，在OTB数据集测试后评估就出现这个错误

改变训练方式，应该不影响评估结果的。OTB100数据集中，有些视频序列中的图像的个数和groundtruth并不一致，你试试https://drive.google.com/drive/folders/1BP7NDhMUQvrgdJSQ8MieVzLRG-mbYkTU这下面的OTB100.json文件，用它测试和评估。

**Comment by Lkevin20** [comment]
作者你好我用的就是这个json文件，出现这个错误


抢哥辣条还想跑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sansanfree/RBO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月9日(星期五) 上午10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12)





  
在作者您源代码的基础上取消了使用IGR loss,只使用CR loss，在Lasot数据集上训练，在OTB数据集测试后评估就出现这个错误
  
改变训练方式，应该不影响评估结果的。OTB100数据集中，有些视频序列中的图像的个数和groundtruth并不一致，你试试https://drive.google.com/drive/folders/1BP7NDhMUQvrgdJSQ8MieVzLRG-mbYkTU这下面的OTB100.json文件，用它测试和评估。

**Comment by sansanfree** [comment]
> 

如果你方便的话，可以将你的OTB100结果发给我，我来看一下。

**Comment by Lkevin20** [comment]
抢哥辣条还想跑
***@***.***



&nbsp;
好的麻烦作者了真的感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sansanfree/RBO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月9日(星期五) 中午11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12)





   
如果你方便的话，可以将你的OTB100结果发给我，我来看一下。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

OTB100.zip (152.25M, 2023年01月08日 11:30 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5b633331e1334e972582b4b41539004e05570704055b5752495304040514060705521e53575b544c520502570b0b060257010a003333322e302102010317480814630e&t=exs_ftn_download&code=dc31392a

**Comment by sansanfree** [comment]
> 抢哥辣条还想跑 ***@***.*** &nbsp; 好的麻烦作者了真的感谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sansanfree/RBO" ***@***.***&gt;; 发送时间:&nbsp;2022年12月9日(星期五) 中午11:16 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 如果你方便的话，可以将你的OTB100结果发给我，我来看一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt; 从QQ邮箱发来的超大附件 OTB100.zip (152.25M, 2023年01月08日 11:30 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5b633331e1334e972582b4b41539004e05570704055b5752495304040514060705521e53575b544c520502570b0b060257010a003333322e302102010317480814630e&t=exs_ftn_download&code=dc31392a

你发我的附件不是跑出来的OTB100结果啊，我这里看是乱码。正常的结果应该是类似这种https://drive.google.com/drive/folders/1Fty4Oaj1TkALsCftMdQSTJW8Rp5210IJ

**Comment by Lkevin20** [comment]
是吗？我正常训练结束包括测试都没有出现问题，这就是生成的结果。辛苦作者了，我检查一下是不是我步骤出现了问题&nbsp;


抢哥辣条还想跑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 下午3:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12)





  
抢哥辣条还想跑 @.*** &nbsp; 好的麻烦作者了真的感谢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sansanfree/RBO" @.&gt;; 发送时间:&nbsp;2022年12月9日(星期五) 中午11:16 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 如果你方便的话，可以将你的OTB100结果发给我，我来看一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 从QQ邮箱发来的超大附件 OTB100.zip (152.25M, 2023年01月08日 11:30 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5b633331e1334e972582b4b41539004e05570704055b5752495304040514060705521e53575b544c520502570b0b060257010a003333322e302102010317480814630e&amp;t=exs_ftn_download&amp;code=dc31392a
  
你发我的附件不是跑出来的OTB100结果啊，我这里看是乱码。正常的结果应该是类似这种https://drive.google.com/drive/folders/1Fty4Oaj1TkALsCftMdQSTJW8Rp5210IJ

**Comment by sansanfree** [comment]
> 是吗？我正常训练结束包括测试都没有出现问题，这就是生成的结果。辛苦作者了，我检查一下是不是我步骤出现了问题&nbsp; 抢哥辣条还想跑 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年12月9日(星期五) 下午3:50 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 抢哥辣条还想跑 @.*** &nbsp; 好的麻烦作者了真的感谢 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sansanfree/RBO" @.&gt;; 发送时间:&nbsp;2022年12月9日(星期五) 中午11:16 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 如果你方便的话，可以将你的OTB100结果发给我，我来看一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 从QQ邮箱发来的超大附件 OTB100.zip (152.25M, 2023年01月08日 11:30 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5b633331e1334e972582b4b41539004e05570704055b5752495304040514060705521e53575b544c520502570b0b060257010a003333322e302102010317480814630e&amp;t=exs_ftn_download&amp;code=dc31392a 你发我的附件不是跑出来的OTB100结果啊，我这里看是乱码。正常的结果应该是类似这种https://drive.google.com/drive/folders/1Fty4Oaj1TkALsCftMdQSTJW8Rp5210IJ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


保存的结果都是txt形式的，就你结果文件不是，而且都100多M，太大了。不客气， 有问题，欢迎询问

**Comment by Lkevin20** [comment]
作者你好，对于这个分类，如果我在你的基础上修改分类rankloss，相比于最原本的siamban交叉熵损失函数，效果也是会好对吧

**Comment by Lkevin20** [comment]
作者你好，我重新训练了模型，但是评估还是会出现相同的问题，不知道是什么地方出现了问题，麻烦作者帮我看一下，这是我在got10k上训练出来的模型，在OTB100数据集上的测试结果。


抢哥辣条还想跑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sansanfree/RBO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月9日(星期五) 下午3:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12)





  
是吗？我正常训练结束包括测试都没有出现问题，这就是生成的结果。辛苦作者了，我检查一下是不是我步骤出现了问题&nbsp; 抢哥辣条还想跑 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年12月9日(星期五) 下午3:50 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 抢哥辣条还想跑 @.*** &nbsp; 好的麻烦作者了真的感谢 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sansanfree/RBO" @.&gt;; 发送时间:&nbsp;2022年12月9日(星期五) 中午11:16 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 如果你方便的话，可以将你的OTB100结果发给我，我来看一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 从QQ邮箱发来的超大附件 OTB100.zip (152.25M, 2023年01月08日 11:30 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5b633331e1334e972582b4b41539004e05570704055b5752495304040514060705521e53575b544c520502570b0b060257010a003333322e302102010317480814630e&amp;amp;t=exs_ftn_download&amp;amp;code=dc31392a 你发我的附件不是跑出来的OTB100结果啊，我这里看是乱码。正常的结果应该是类似这种https://drive.google.com/drive/folders/1Fty4Oaj1TkALsCftMdQSTJW8Rp5210IJ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
保存的结果都是txt形式的，就你结果文件不是，而且都100多M，太大了。不客气， 有问题，欢迎询问

**Comment by sansanfree** [comment]
> 作者你好，我重新训练了模型，但是评估还是会出现相同的问题，不知道是什么地方出现了问题，麻烦作者帮我看一下，这是我在got10k上训练出来的模型，在OTB100数据集上的测试结果。 抢哥辣条还想跑 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sansanfree/RBO" ***@***.***&gt;; 发送时间:&nbsp;2022年12月9日(星期五) 下午3:57 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 是吗？我正常训练结束包括测试都没有出现问题，这就是生成的结果。辛苦作者了，我检查一下是不是我步骤出现了问题&nbsp; 抢哥辣条还想跑 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年12月9日(星期五) 下午3:50 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 抢哥辣条还想跑 @.*** &nbsp; 好的麻烦作者了真的感谢 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sansanfree/RBO" @.&gt;; 发送时间:&nbsp;2022年12月9日(星期五) 中午11:16 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 如果你方便的话，可以将你的OTB100结果发给我，我来看一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 从QQ邮箱发来的超大附件 OTB100.zip (152.25M, 2023年01月08日 11:30 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5b633331e1334e972582b4b41539004e05570704055b5752495304040514060705521e53575b544c520502570b0b060257010a003333322e302102010317480814630e&amp;amp;t=exs_ftn_download&amp;amp;code=dc31392a 你发我的附件不是跑出来的OTB100结果啊，我这里看是乱码。正常的结果应该是类似这种https://drive.google.com/drive/folders/1Fty4Oaj1TkALsCftMdQSTJW8Rp5210IJ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 保存的结果都是txt形式的，就你结果文件不是，而且都100多M，太大了。不客气， 有问题，欢迎询问 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我看不到附件信息，你就看能不能生成结果文件，是.txt格式的。不是的话，再去调试检查，可能是路径等问题。

**Comment by Lkevin20** [comment]
有的有的


抢哥辣条还想跑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sansanfree/RBO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月13日(星期二) 中午12:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12)





  
作者你好，我重新训练了模型，但是评估还是会出现相同的问题，不知道是什么地方出现了问题，麻烦作者帮我看一下，这是我在got10k上训练出来的模型，在OTB100数据集上的测试结果。 抢哥辣条还想跑 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sansanfree/RBO" @.&gt;; 发送时间:&nbsp;2022年12月9日(星期五) 下午3:57 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 是吗？我正常训练结束包括测试都没有出现问题，这就是生成的结果。辛苦作者了，我检查一下是不是我步骤出现了问题&nbsp; 抢哥辣条还想跑 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年12月9日(星期五) 下午3:50 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 抢哥辣条还想跑 @.*** &nbsp; 好的麻烦作者了真的感谢 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sansanfree/RBO" @.&gt;; 发送时间:&nbsp;2022年12月9日(星期五) 中午11:16 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 如果你方便的话，可以将你的OTB100结果发给我，我来看一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 从QQ邮箱发来的超大附件 OTB100.zip (152.25M, 2023年01月08日 11:30 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5b633331e1334e972582b4b41539004e05570704055b5752495304040514060705521e53575b544c520502570b0b060257010a003333322e302102010317480814630e&amp;amp;amp;t=exs_ftn_download&amp;amp;amp;code=dc31392a 你发我的附件不是跑出来的OTB100结果啊，我这里看是乱码。正常的结果应该是类似这种https://drive.google.com/drive/folders/1Fty4Oaj1TkALsCftMdQSTJW8Rp5210IJ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 保存的结果都是txt形式的，就你结果文件不是，而且都100多M，太大了。不客气， 有问题，欢迎询问 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
我看不到附件信息，你就看能不能生成结果文件，是.txt格式的。不是的话，再去调试检查，可能是路径等问题。

**Comment by sansanfree** [comment]
> 有的有的 抢哥辣条还想跑 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sansanfree/RBO" ***@***.***&gt;; 发送时间:&nbsp;2022年12月13日(星期二) 中午12:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 作者你好，我重新训练了模型，但是评估还是会出现相同的问题，不知道是什么地方出现了问题，麻烦作者帮我看一下，这是我在got10k上训练出来的模型，在OTB100数据集上的测试结果。 抢哥辣条还想跑 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sansanfree/RBO" @.&gt;; 发送时间:&nbsp;2022年12月9日(星期五) 下午3:57 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 是吗？我正常训练结束包括测试都没有出现问题，这就是生成的结果。辛苦作者了，我检查一下是不是我步骤出现了问题&nbsp; 抢哥辣条还想跑 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年12月9日(星期五) 下午3:50 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 抢哥辣条还想跑 @.*** &nbsp; 好的麻烦作者了真的感谢 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sansanfree/RBO" @.&gt;; 发送时间:&nbsp;2022年12月9日(星期五) 中午11:16 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 如果你方便的话，可以将你的OTB100结果发给我，我来看一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 从QQ邮箱发来的超大附件 OTB100.zip (152.25M, 2023年01月08日 11:30 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5b633331e1334e972582b4b41539004e05570704055b5752495304040514060705521e53575b544c520502570b0b060257010a003333322e302102010317480814630e&amp;amp;amp;t=exs_ftn_download&amp;amp;amp;code=dc31392a 你发我的附件不是跑出来的OTB100结果啊，我这里看是乱码。正常的结果应该是类似这种https://drive.google.com/drive/folders/1Fty4Oaj1TkALsCftMdQSTJW8Rp5210IJ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 保存的结果都是txt形式的，就你结果文件不是，而且都100多M，太大了。不客气， 有问题，欢迎询问 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 我看不到附件信息，你就看能不能生成结果文件，是.txt格式的。不是的话，再去调试检查，可能是路径等问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你要是跑我提供的权重文件，会有问题吗

**Comment by Lkevin20** [comment]
解决了，是测试结果路径错误了，谢谢作者了

**Comment by Lkevin20** [comment]
作者你好，请问我将这几行代码注释掉了是不是就是不使用rankloss策略，使用的就只是siamban网络中的分类和回归的loss。因为我训练发现注释这几行代码前后结果基本一致。一个结果是0.653，另一个结果是0.654


抢哥辣条还想跑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sansanfree/RBO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月15日(星期四) 晚上7:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12)





  
有的有的 抢哥辣条还想跑 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sansanfree/RBO" @.&gt;; 发送时间:&nbsp;2022年12月13日(星期二) 中午12:30 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 作者你好，我重新训练了模型，但是评估还是会出现相同的问题，不知道是什么地方出现了问题，麻烦作者帮我看一下，这是我在got10k上训练出来的模型，在OTB100数据集上的测试结果。 抢哥辣条还想跑 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sansanfree/RBO" @.&gt;; 发送时间:&nbsp;2022年12月9日(星期五) 下午3:57 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 是吗？我正常训练结束包括测试都没有出现问题，这就是生成的结果。辛苦作者了，我检查一下是不是我步骤出现了问题&nbsp; 抢哥辣条还想跑 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年12月9日(星期五) 下午3:50 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 抢哥辣条还想跑 @.*** &nbsp; 好的麻烦作者了真的感谢 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sansanfree/RBO" @.&gt;; 发送时间:&nbsp;2022年12月9日(星期五) 中午11:16 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [sansanfree/RBO] 作者你好在评估时出现这个问题，请问您是怎么解决的呢 (Issue #12) 如果你方便的话，可以将你的OTB100结果发给我，我来看一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 从QQ邮箱发来的超大附件 OTB100.zip (152.25M, 2023年01月08日 11:30 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5b633331e1334e972582b4b41539004e05570704055b5752495304040514060705521e53575b544c520502570b0b060257010a003333322e302102010317480814630e&amp;amp;amp;amp;t=exs_ftn_download&amp;amp;amp;amp;code=dc31392a 你发我的附件不是跑出来的OTB100结果啊，我这里看是乱码。正常的结果应该是类似这种https://drive.google.com/drive/folders/1Fty4Oaj1TkALsCftMdQSTJW8Rp5210IJ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 保存的结果都是txt形式的，就你结果文件不是，而且都100多M，太大了。不客气， 有问题，欢迎询问 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 我看不到附件信息，你就看能不能生成结果文件，是.txt格式的。不是的话，再去调试检查，可能是路径等问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
你要是跑我提供的权重文件，会有问题吗

**Comment by Lkevin20** [comment]
作者你好，我取消了rankloss,效果却比使用rankloss好，这是为什么呀？

**Comment by sansanfree** [comment]
> 作者你好，我取消了rankloss,效果却比使用rankloss好，这是为什么呀？

第一，我看不到你发的附件具体信息；第二，除了GOT-10K测试集，其他测试集都需要在GOT-10K、Youtube-BB、LaSOT、COCO、ImageDET和ImageVID上联合训练（这是siamban规定的），单独的GOT-10K训练集训练时不行的。
